### ISSUE TITLE
Add way to rename joint_states

### ISSUE THREAD

**Issue by guihomework** [robomantic/agni_serial_protocol#4]
Currently the `Sensor_tactile_glove_teensy_bend` parser implementation uses hard-coded joint names following the pattern _bend_#_

with resulting `JointState` msg looking like this 

```
---
header: 
  seq: 229749
  stamp: 
    secs: 1669749347
    nsecs: 244204776
  frame_id: ''
name: 
  - bend_1
  - bend_2
  - bend_3
  - bend_4
  - bend_5
  - bend_6
  - bend_7
  - bend_8
  - bend_9
  - bend_10
  - bend_11
  - bend_12
  - bend_13
  - bend_14
  - bend_15
  - bend_16
position: [14.086956024169922, -23.490001678466797, 1.2149534225463867, 1.1440677642822266, -1.8000000715255737, 8.43356704711914, 2.4387097358703613, -6.155172824859619, -8.550000190734863, -12.59999942779541, 3.049999952316284, -0.8166666626930237, -15.75, 47.880001068115234, 20.88888931274414, 42.66666793823242]
velocity: []
effort: []
---
```

The idea is to permit to tell the driver to use a specific mapping for the _joint_names_ (index to name). If none is provided, the existing naming scheme is used.

This would help have more meaningful human-readable data, and help calibration tools to process the data. 
Additionally, the mapping between index and specific posture measurement depends on the glove (wiring issue), which means each glove would have its own mapping when starting and so be hidden from the user just seeing the correct _joint_names_.

Remark: For the sake of backward compatibility, one could make sure the order of the sensors is kept, in case some software was using the index of the vector and not the name.
